version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: wind_turbine_db
    environment:
      POSTGRES_USER: scada_admin
      POSTGRES_PASSWORD: enterprise_password
      POSTGRES_DB: turbine_telemetry
    ports:
      - "5433:5432" 
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../data:/data  # Mounts your local CSV data folder into the container
      - ../sql:/sql    # Mounts your SQL scripts into the container
    restart: unless-stopped

volumes:
  pg_data:
